query ContactPage {
	contactPage {
		overskrift
		kontaktEmail
		googleMapsLink
		kort {
			responsiveImage(imgixParams: { ar: "16:9", auto: format, crop: focalpoint, fit: crop }) {
				width
				webpSrcSet
				title
				srcSet
				src
				sizes
				height
				bgColor
				base64
				aspectRatio
				alt
			}
		}
		contactPersons {
			avatar {
				responsiveImage(imgixParams: { ar: "1:1", auto: format, fit: crop, crop: focalpoint }) {
					alt
					aspectRatio
					base64
					bgColor
					height
					sizes
					src
					srcSet
					title
					webpSrcSet
					width
				}
			}
			jobArea
			jobTitle
			name
		}
		_seoMetaTags {
			tag
			attributes
			content
			__typename
		}
	}
}
