query Frontpage {
	forside {
		image {
			url
			responsiveImage(imgixParams: { auto: format, fit: crop, crop: focalpoint, ar: "16:9" }) {
				srcSet
				webpSrcSet
				sizes
				src
				width
				height
				aspectRatio
				alt
				title
				__typename
			}
		}
		overskrift
		text
		slug
		seo {
			description
			title
			twitterCard
			image {
				url
			}
		}
		citater {
			qouteText
			reference
			id
			avatar {
				responsiveImage(imgixParams: { auto: format, fit: crop, crop: focalpoint, ar: "1:1" }) {
					srcSet
					webpSrcSet
					sizes
					src
					width
					height
					aspectRatio
					alt
					title
					__typename
				}
			}
		}
		usp {
			text
			id
		}
		_seoMetaTags {
			tag
			attributes
			content
			__typename
		}
	}
}
