query LandingPage {
	landingPage {
		introImage {
			...ImageFragment
		}
		overskrift
		slug
		seo {
			title
			twitterCard
			description
			image {
				url
			}
		}
		blokListe {
			...BlockListFrament
		}
	}
}
