query Menu {
	menu {
		mainMenu {
			link {
				...LinkFragment
			}
		}
		productMenu {
			menuLink {
				...LinkFragment
			}
			childMenuLinks {
				link {
					...LinkFragment
				}
			}
		}
	}
}
