query Products {
	allProductPages(first: 99) {
		__typename
		slug
		introText
		overskrift
		icon {
			...ImageFragment
		}
		introImage {
			...ImageFragment
		}
		parent {
			slug
		}
		children {
			id
		}
	}
}
