fragment LinkFragment on LinkBlockModelLinkField {
	... on ContactPageRecord {
		id
		slug
		headline
	}
	... on ForsideRecord {
		id
		slug
		overskrift
	}
	... on LandingPageRecord {
		id
		slug
		overskrift
	}
	... on NewsPageRecord {
		id
		overskrift
		slug
		parent {
			slug
			parent {
				slug
			}
		}
	}
	... on ProductPageRecord {
		id
		overskrift
		slug
		parent {
			slug
			parent {
				slug
			}
		}
	}
}
