fragment LinkFragment on LinkBlockModelLinkField {
	... on ForsideRecord {
		__typename
		id
		slug
		overskrift
	}
	... on ProductPageRecord {
		__typename
		id
		overskrift
		slug
		parent {
			slug
			parent {
				slug
			}
		}
	}
	... on ContactPageRecord {
		__typename
		id
		overskrift
		slug
	}
	... on ForsideRecord {
		__typename
		id
		overskrift
		slug
	}
	... on CaseRecord {
		__typename
		id
		overskrift
		slug
	}
	... on CaseoverviewRecord {
		__typename
		id
		overskrift
		slug
	}
}
